/**
 * Looks up map coordinates for every street address in src/data.js using the
 * U.S. Census Bureau Geocoder (public domain, no key) and writes them to
 * src/places.js. Run it whenever an address is added or changed:
 *
 *   npm run geocode
 *
 * Only addresses that start with a house number are sent. Confidential
 * locations are never sent. Addresses the Census cannot match are reported and
 * left out, so the site falls back to an approximate ZIP-based distance.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { events, resources } from '../src/data.js'
import { hasStreetAddress } from '../src/distance.js'

const ENDPOINT = 'https://geocoding.geo.census.gov/geocoder/locations/onelineaddress'
const OUTPUT = fileURLToPath(new URL('../src/places.js', import.meta.url))

export function addressesToGeocode(items) {
  const addresses = new Set()
  for (const item of items) {
    if (item.confidentialLocation) continue
    const text = item.address || item.location || ''
    if (hasStreetAddress(text)) addresses.add(text)
  }
  return [...addresses].sort()
}

export async function geocodeAddress(address, fetchImpl = fetch) {
  const url = `${ENDPOINT}?${new URLSearchParams({ address, benchmark: 'Public_AR_Current', format: 'json' })}`
  const response = await fetchImpl(url)
  if (!response.ok) throw new Error(`Census geocoder returned ${response.status}`)
  const payload = await response.json()
  const match = payload?.result?.addressMatches?.[0]
  if (!match?.coordinates) return null
  return {
    lat: Math.round(match.coordinates.y * 1e6) / 1e6,
    lng: Math.round(match.coordinates.x * 1e6) / 1e6,
    matched: match.matchedAddress,
  }
}

export async function buildPlaces(items, fetchImpl = fetch, log = console.log) {
  const places = {}
  const misses = []
  for (const address of addressesToGeocode(items)) {
    const result = await geocodeAddress(address, fetchImpl)
    if (result) {
      places[address] = result
      log(`  matched  ${address}\n           -> ${result.matched} (${result.lat}, ${result.lng})`)
    } else {
      misses.push(address)
      log(`  no match ${address}`)
    }
    await new Promise((resolve) => setTimeout(resolve, 250))
  }
  return { places, misses }
}

export function renderModule(places) {
  return `/**
 * Generated by \`npm run geocode\` from the U.S. Census Bureau Geocoder
 * (public domain). Do not edit by hand; change the address in data.js and
 * rerun the script. Addresses missing here fall back to ZIP-based distances.
 */
export const GEOCODED = ${JSON.stringify(places, null, 2)}
`
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]
if (isMain) {
  console.log('Geocoding street addresses with the U.S. Census Bureau...')
  const { places, misses } = await buildPlaces([...resources, ...events])
  const previous = await readFile(OUTPUT, 'utf8').catch(() => '')
  const next = renderModule(places)
  await writeFile(OUTPUT, next)
  console.log(`\nWrote ${Object.keys(places).length} places to src/places.js${previous === next ? ' (unchanged)' : ''}.`)
  if (misses.length) {
    console.log(`Check these ${misses.length} address(es); they will use ZIP-based distances:`)
    misses.forEach((address) => console.log(`  - ${address}`))
    process.exitCode = 1
  }
}
