export const categories = [
  { id: 'basic-needs', label: 'Basic needs', labelEs: 'Necesidades básicas', blurb: 'Food, bills and essentials' },
  { id: 'children', label: 'Children & youth', labelEs: 'Niños y jóvenes', blurb: 'Learning, care and activities' },
  { id: 'families', label: 'Families', labelEs: 'Familias', blurb: 'Parenting and child care' },
  { id: 'health', label: 'Health & wellness', labelEs: 'Salud y bienestar', blurb: 'Medical and mental health' },
  { id: 'older-adults', label: 'Older adults', labelEs: 'Adultos mayores', blurb: 'Aging with support' },
  { id: 'jobs', label: 'Jobs & money', labelEs: 'Empleo y finanzas', blurb: 'Training and financial stability' },
  { id: 'housing', label: 'Housing', labelEs: 'Vivienda', blurb: 'Rent, utilities and shelter' },
  { id: 'transportation', label: 'Transportation', labelEs: 'Transporte', blurb: 'Rides and mobility' },
  { id: 'community', label: 'Community life', labelEs: 'Vida comunitaria', blurb: 'Parks, programs and connection' },
  { id: 'education', label: 'Education', labelEs: 'Educación', blurb: 'Schools and lifelong learning' },
]

export const resources = [
  {
    id: 'nc-211',
    name: 'NC 211',
    category: 'basic-needs',
    audiences: ['All ages', 'All residents'],
    description: 'Free, confidential help finding verified food, housing, health care, transportation and other services across North Carolina.',
    descriptionEs: 'Ayuda gratuita y confidencial para encontrar alimentos, vivienda, atención médica, transporte y otros servicios verificados.',
    details: 'Call 2-1-1 to speak with a Community Resource Specialist or search online. Support is available 24 hours a day, every day, in most languages.',
    phone: '211',
    alternatePhone: '888-892-1162',
    hours: 'Open 24 hours',
    cost: 'Free',
    languages: ['English', 'Spanish', 'Language support'],
    accessibility: ['Phone support', 'Online search'],
    location: 'Statewide, including Waxhaw',
    source: 'NC 211',
    sourceUrl: 'https://nc211.org/about/',
    verified: 'September 11, 2026',
    featured: true,
    alwaysOpen: true,
    keywords: ['rent', 'utility', 'food', 'shelter', 'crisis', 'benefits', 'help', 'referral'],
  },
  {
    id: 'union-economic-services',
    name: 'Union County Economic Services',
    category: 'basic-needs',
    audiences: ['Adults', 'Families', 'Older adults'],
    description: 'Apply for Food and Nutrition Services, Medicaid, child care assistance, emergency energy help and other financial-stability programs.',
    descriptionEs: 'Solicite asistencia alimentaria, Medicaid, ayuda para cuidado infantil, energía de emergencia y otros programas financieros.',
    details: 'Union County Social Services accepts applications for benefit programs and helps residents report changes to existing cases. Eligibility varies by program.',
    phone: '704-296-4300',
    hours: 'Monday-Friday, 8:00 AM-5:00 PM',
    schedule: { days: [1, 2, 3, 4, 5], start: 8, end: 17 },
    cost: 'Free to apply',
    languages: ['English', 'Spanish forms'],
    accessibility: ['Accessible office', 'Online application'],
    location: '2330 Concord Avenue, Monroe, NC 28110',
    source: 'Union County Social Services',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-r-z/social-services/economic-services',
    verified: 'September 11, 2026',
    featured: true,
    keywords: ['snap', 'ebt', 'food stamps', 'medicaid', 'childcare', 'utilities', 'lieap', 'bills', 'benefits'],
  },
  {
    id: 'union-public-health',
    name: 'Union County Public Health Clinical Services',
    category: 'health',
    audiences: ['Children', 'Adults', 'Families', 'All residents'],
    description: 'Community clinics for immunizations, dental care, family planning, maternal health, sexual health, tuberculosis treatment and more.',
    descriptionEs: 'Clínicas comunitarias de vacunas, odontología, planificación familiar, salud materna, salud sexual y tratamiento de tuberculosis.',
    details: 'Several services welcome uninsured residents. Eligibility and fees vary, so call the clinic before visiting.',
    phone: '704-296-4800',
    hours: 'Call for clinic hours',
    cost: 'Varies by service',
    languages: ['English', 'Language assistance'],
    accessibility: ['Accessible office', 'Confidential services'],
    location: '2330 Concord Avenue, Monroe, NC 28110',
    source: 'Union County Public Health',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-f-p/public-health/clinical-services',
    verified: 'September 11, 2026',
    featured: true,
    keywords: ['doctor', 'clinic', 'vaccine', 'dental', 'pregnancy', 'wic', 'uninsured', 'testing'],
  },
  {
    id: 'union-wic',
    name: 'Union County WIC',
    category: 'families',
    audiences: ['Pregnant people', 'Parents', 'Children under 5'],
    description: 'Nutrition, healthy-food and breastfeeding support for eligible pregnant people, new parents, infants and young children.',
    descriptionEs: 'Apoyo de nutrición, alimentos saludables y lactancia para personas embarazadas, padres, bebés y niños pequeños elegibles.',
    details: 'WIC services are free. Contact Union County Public Health to ask about eligibility and appointments.',
    phone: '704-296-4800',
    hours: 'Call for appointments',
    cost: 'Free for eligible families',
    languages: ['English', 'Spanish', 'Language assistance'],
    accessibility: ['Accessible office'],
    location: '2330 Concord Avenue, Monroe, NC 28110',
    source: 'Union County Public Health',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-f-p/public-health/clinical-services',
    verified: 'September 11, 2026',
    keywords: ['baby', 'infant', 'pregnant', 'nutrition', 'breastfeeding', 'food'],
  },
  {
    id: 'union-transportation',
    name: 'Union County Transportation',
    category: 'transportation',
    audiences: ['Age 16+', 'Medicaid members', 'Veterans', 'Older adults'],
    description: 'Demand-response transportation for eligible trips including medical appointments, work, errands and community activities.',
    descriptionEs: 'Transporte bajo demanda para viajes elegibles, incluidas citas médicas, trabajo, mandados y actividades comunitarias.',
    details: 'Programs have different eligibility and scheduling rules. Medicaid transportation can serve eligible residents of any age.',
    phone: '704-292-2511',
    hours: 'Call ahead to schedule',
    cost: 'Varies by program',
    languages: ['English'],
    accessibility: ['Mobility assistance', 'Advance scheduling'],
    location: 'Serves Union County',
    source: 'Union County Transportation',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-r-z/transportation/rider-s-guide',
    verified: 'September 11, 2026',
    keywords: ['ride', 'bus', 'medical transport', 'doctor', 'mobility', 'veteran', 'medicaid'],
  },
  {
    id: 'senior-nutrition',
    name: 'Union County Senior Nutrition Program',
    category: 'older-adults',
    audiences: ['Age 60+', 'Caregivers'],
    description: 'Nutritious meals through community dining sites and home delivery for eligible Union County residents age 60 and older.',
    descriptionEs: 'Comidas nutritivas en sitios comunitarios y entrega a domicilio para residentes elegibles de 60 años o más.',
    details: 'Home-delivery clients may be placed on a waiting list. Referrals and wellness checks help connect older residents with support.',
    phone: '704-283-3500',
    hours: 'Monday-Friday',
    cost: 'Call for eligibility',
    languages: ['English'],
    accessibility: ['Home delivery', 'Caregiver referrals'],
    location: 'Serves Union County',
    source: 'Union County Community Support & Outreach',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-a-e/community-support-outreach/senior-residents',
    verified: 'September 11, 2026',
    keywords: ['meals on wheels', 'senior food', 'aging', 'homebound', 'lunch'],
  },
  {
    id: 'southwest-library',
    name: 'Southwest Regional Library',
    category: 'education',
    audiences: ['Children', 'Teens', 'Adults', 'Older adults'],
    description: 'A Waxhaw library with expanded collections, children’s spaces, a STEAM lab, study rooms, technology and community programs.',
    descriptionEs: 'Biblioteca de Waxhaw con colecciones, espacios infantiles, laboratorio STEAM, salas de estudio, tecnología y programas comunitarios.',
    details: 'The approximately 19,000-square-foot branch offers space to learn, work, gather and access technology.',
    phone: '704-283-8184',
    hours: 'See library schedule',
    cost: 'Free',
    languages: ['English', 'Multilingual materials'],
    accessibility: ['Accessible building', 'Technology access', 'Study rooms'],
    location: '1515 Cuthbertson Road, Waxhaw, NC 28173',
    source: 'Union County Government',
    sourceUrl: 'https://www.unioncountync.gov/Home/Components/News/News/1433/339',
    verified: 'September 11, 2026',
    featured: true,
    keywords: ['books', 'computer', 'wifi', 'homework', 'study', 'storytime', 'steam'],
  },
  {
    id: 'waxhaw-parks',
    name: 'Waxhaw Parks & Recreation',
    category: 'community',
    audiences: ['All ages', 'All abilities'],
    description: 'Recreational, educational and cultural programs, public parks and community events designed for residents of all ages and abilities.',
    descriptionEs: 'Programas recreativos, educativos y culturales, parques públicos y eventos para residentes de todas las edades y capacidades.',
    details: 'The department manages parks, programs and town events and partners with local and regional organizations.',
    phone: '704-843-2195',
    hours: 'Monday-Friday, 8:00 AM-5:00 PM',
    schedule: { days: [1, 2, 3, 4, 5], start: 8, end: 17 },
    cost: 'Many free options',
    languages: ['English'],
    accessibility: ['Inclusive programs', 'Accessible amenities vary'],
    location: '8607 Kensington Drive, Waxhaw, NC 28173',
    source: 'Town of Waxhaw',
    sourceUrl: 'https://www.waxhaw.com/government/departments/parks-and-recreation',
    verified: 'September 11, 2026',
    keywords: ['park', 'playground', 'sports', 'recreation', 'art', 'festival', 'programs'],
  },
  {
    id: 'waxhaw-public-services',
    name: 'Waxhaw Public Services',
    category: 'housing',
    audiences: ['Residents', 'Property owners'],
    description: 'Information and assistance for trash, recycling, yard debris, seasonal leaf collection, trees, streets and sidewalks.',
    descriptionEs: 'Información y ayuda sobre basura, reciclaje, residuos de jardín, recolección de hojas, árboles, calles y aceras.',
    details: 'The Town coordinates weekly trash and biweekly recycling and maintains public streets, sidewalks and downtown grounds.',
    phone: '704-843-7439',
    hours: 'Monday-Friday, 7:00 AM-4:00 PM',
    schedule: { days: [1, 2, 3, 4, 5], start: 7, end: 16 },
    cost: 'Resident service',
    languages: ['English'],
    accessibility: ['Phone assistance', 'Online forms'],
    location: '8607 Kensington Drive, Waxhaw, NC 28173',
    source: 'Town of Waxhaw',
    sourceUrl: 'https://www.waxhaw.com/government/departments/public-services',
    verified: 'September 11, 2026',
    keywords: ['trash', 'garbage', 'recycling', 'leaves', 'streetlight', 'sidewalk'],
  },
  {
    id: 'common-heart',
    name: 'Common Heart Food Pantries',
    category: 'basic-needs',
    audiences: ['Individuals', 'Families', 'Older adults'],
    description: 'Weekly food pantries for qualifying Union County residents, including a Wednesday location in Waxhaw and delivery for residents facing transportation barriers.',
    descriptionEs: 'Despensas semanales para residentes elegibles, incluida una ubicación los miércoles en Waxhaw y entrega para quienes tienen barreras de transporte.',
    details: 'Traditional pantries provide food through TEFAP. The Common Cupboard delivery program serves qualifying Union County residents who cannot attend evening pantries.',
    phone: '980-443-3841',
    hours: 'Schedules vary by pantry',
    cost: 'Free for eligible residents',
    languages: ['English'],
    accessibility: ['Delivery for eligible residents', 'Multiple locations'],
    location: 'Waxhaw and Union County locations',
    source: 'Common Heart',
    sourceUrl: 'https://commonheart.org/programs/',
    verified: 'September 11, 2026',
    featured: true,
    keywords: ['food pantry', 'groceries', 'delivery', 'tefap', 'hunger', 'volunteer'],
  },
  {
    id: 'ray-of-hope',
    name: "Waxhaw's Ray of Hope Food Pantry",
    category: 'basic-needs',
    audiences: ['Individuals', 'Families'],
    description: 'A local food pantry serving eligible individuals and families and coordinating community food drives.',
    descriptionEs: 'Despensa local que sirve a personas y familias elegibles y coordina colectas comunitarias de alimentos.',
    details: 'The pantry states that it serves eligible people regardless of race, color, religion, national origin, age, sex or disability. Call before visiting to confirm current arrangements.',
    phone: '704-248-1017',
    hours: 'Monday-Friday, 11:00 AM-6:00 PM',
    schedule: { days: [1, 2, 3, 4, 5], start: 11, end: 18 },
    cost: 'Free for eligible residents',
    languages: ['English'],
    accessibility: ['Call for accommodations'],
    location: 'Waxhaw, NC',
    source: "Waxhaw's Ray of Hope",
    sourceUrl: 'https://waxhawsrayofhope.wixsite.com/waxhaws-ray-of-hope/food-pantry',
    verified: 'September 11, 2026',
    keywords: ['food pantry', 'groceries', 'hunger', 'food drive'],
  },
  {
    id: 'turning-point',
    name: 'Turning Point',
    category: 'housing',
    audiences: ['Survivors', 'Adults', 'Children', 'Families'],
    description: 'Free emergency shelter, crisis response and advocacy for survivors of domestic violence, sexual assault and child abuse in Union County.',
    descriptionEs: 'Refugio de emergencia, respuesta a crisis y defensa gratuitas para sobrevivientes de violencia doméstica, agresión sexual y abuso infantil.',
    details: 'The shelter location is confidential for safety. Turning Point provides crisis intervention, safety planning, counseling, court advocacy and children’s services.',
    phone: '704-283-7233',
    alternatePhone: '704-283-7770',
    hours: 'Crisis lines open 24 hours',
    cost: 'Free',
    languages: ['English', 'Call for language support'],
    accessibility: ['Confidential shelter', 'Crisis advocacy'],
    location: 'Confidential location, Union County',
    confidentialLocation: true,
    source: 'Turning Point',
    sourceUrl: 'https://turningpointnc.org/',
    verified: 'September 11, 2026',
    alwaysOpen: true,
    urgent: true,
    keywords: ['domestic violence', 'sexual assault', 'abuse', 'safe shelter', 'crisis', 'escape'],
  },
  {
    id: 'work-first',
    name: 'Union County Work First',
    category: 'jobs',
    audiences: ['Families', 'Parents', 'Job seekers'],
    description: 'Temporary financial support and employment services that help families work toward stability and self-sufficiency.',
    descriptionEs: 'Apoyo financiero temporal y servicios de empleo para ayudar a las familias a lograr estabilidad y autosuficiencia.',
    details: 'The program focuses on job readiness, employment, child well-being and family health. Applications can be submitted online or by email.',
    phone: '704-296-4300',
    hours: 'Monday-Friday, 8:00 AM-5:00 PM',
    schedule: { days: [1, 2, 3, 4, 5], start: 8, end: 17 },
    cost: 'Free to apply',
    languages: ['English', 'Spanish forms'],
    accessibility: ['Online application', 'Accessible office'],
    location: 'Serves Union County',
    source: 'Union County Community Support & Outreach',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-a-e/community-support-outreach/work-first',
    verified: 'September 11, 2026',
    keywords: ['job', 'cash assistance', 'employment', 'training', 'parents', 'benefits'],
  },
  {
    id: 'child-care-subsidy',
    name: 'Union County Child Care Subsidy',
    category: 'families',
    audiences: ['Parents', 'Caregivers', 'Children'],
    description: 'Income-based assistance with child care costs for eligible families who have a qualifying child care need.',
    descriptionEs: 'Ayuda basada en ingresos para cubrir el cuidado infantil de familias elegibles con una necesidad calificada.',
    details: 'The program also helps parents understand how to select safe, quality child care. Contact the county’s vendor to ask about current eligibility.',
    phone: '704-706-9494',
    hours: 'Call for assistance',
    cost: 'Income-based assistance',
    languages: ['English'],
    accessibility: ['Phone assistance'],
    location: 'Serves Union County',
    source: 'Union County Social Services',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-r-z/social-services/economic-services',
    verified: 'September 11, 2026',
    keywords: ['daycare', 'childcare', 'preschool', 'babysitting', 'working parent'],
  },
  {
    id: 'ucps-family-resources',
    name: 'UCPS Community & Mental Health Resources',
    category: 'children',
    audiences: ['Students', 'Parents', 'Caregivers'],
    description: 'A school-system resource collection connecting students and families with community and behavioral-health support.',
    descriptionEs: 'Colección del sistema escolar que conecta a estudiantes y familias con apoyo comunitario y de salud mental.',
    details: 'The guide includes local social services, child and family supports, behavioral-health providers and crisis resources.',
    phone: '704-296-9898',
    hours: 'See school-system information',
    cost: 'Information is free',
    languages: ['English'],
    accessibility: ['Online directory', 'School support'],
    location: 'Serves Union County Public Schools families',
    source: 'Union County Public Schools',
    sourceUrl: 'https://fhhs.ucpsnc.org/students-families/parent-resources/community-mental-health-resources',
    verified: 'September 11, 2026',
    keywords: ['school', 'student', 'counseling', 'mental health', 'parent', 'teen'],
  },
  {
    id: 'veterans-services',
    name: 'Union County Veterans Services',
    category: 'older-adults',
    audiences: ['Veterans', 'Service members', 'Families'],
    description: 'County assistance connecting veterans and their families with benefits, services and eligible transportation.',
    descriptionEs: 'Ayuda del condado para conectar a veteranos y sus familias con beneficios, servicios y transporte elegible.',
    details: 'Contact the office to ask about benefits counseling and documentation needed for an appointment.',
    phone: '704-283-3807',
    hours: 'Call for an appointment',
    cost: 'Free assistance',
    languages: ['English'],
    accessibility: ['Office assistance', 'Transportation referrals'],
    location: '407 North Main Street, Monroe, NC 28112',
    source: 'Union County Government',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-f-p/public-communications/union-county-office-addresses-and-phone-numbers',
    verified: 'September 11, 2026',
    keywords: ['veteran', 'military', 'benefits', 'va', 'service member'],
  },
  {
    id: 'atrium-waxhaw',
    name: 'Atrium Health Waxhaw Emergency Department',
    category: 'health',
    audiences: ['All ages', 'All residents'],
    description: 'A freestanding emergency department in Waxhaw with emergency physicians and advanced diagnostic services.',
    descriptionEs: 'Departamento de emergencias independiente en Waxhaw con médicos de emergencia y servicios de diagnóstico avanzados.',
    details: 'For life-threatening emergencies, call 911. This listing is for emergency medical care, not routine primary care.',
    phone: '911',
    hours: 'Emergency care open 24 hours',
    cost: 'Insurance and fees vary',
    languages: ['English', 'Language assistance'],
    accessibility: ['Accessible facility', 'Emergency care'],
    location: '2700 Providence Road South, Waxhaw, NC 28173',
    source: 'Union County Health and Wellness Resource Guide',
    sourceUrl: 'https://www.unioncountync.gov/home/showpublisheddocument/1178/639148218369100000',
    verified: 'September 11, 2026',
    alwaysOpen: true,
    urgent: true,
    keywords: ['hospital', 'emergency room', 'er', 'urgent medical', 'injury'],
  },
]

export const events = [
  {
    id: 'jammin-tracks-sept',
    title: "Jammin' By The Tracks",
    date: '2026-09-18',
    time: '7:00 PM-9:00 PM',
    location: 'Community Corner, 115 McDonald Street',
    category: 'Music',
    description: 'A free outdoor concert under the Water Tank featuring Darren Deese.',
    sourceUrl: 'https://www.waxhaw.com/our-town/events/jammin-by-the-tracks',
    address: '115 McDonald Street, Waxhaw, NC 28173',
    accessibility: 'Outdoor venue; contact organizers for accommodations.',
  },
  {
    id: 'library-board-sept',
    title: 'Union County Library Board Meeting',
    date: '2026-09-15',
    time: '5:30 PM',
    location: 'Southwest Regional Library, Waxhaw',
    category: 'Civic',
    description: 'A scheduled public meeting of the Union County Library Board of Trustees.',
    sourceUrl: 'https://www.unioncountync.gov/government/boards-committees/board-of-county-commissioners/commissioner-appointments-to-boards-committees',
    address: '1515 Cuthbertson Road, Waxhaw, NC 28173',
    accessibility: 'Accessible public building.',
  },
  {
    id: 'autumn-treasures',
    title: 'Autumn Treasures',
    date: '2026-10-10',
    time: '10:00 AM-6:00 PM',
    location: 'Downtown Waxhaw',
    category: 'Festival',
    description: 'Waxhaw’s annual festival with local makers, music, food and a family area. Admission is free.',
    sourceUrl: 'https://www.waxhaw.com/our-town/events/autumn-treasures',
    address: 'Downtown Waxhaw, NC 28173',
    accessibility: 'ADA parking is listed by the Town of Waxhaw.',
  },
  {
    id: 'christmas-parade',
    title: 'Waxhaw Christmas Parade',
    date: '2026-12-13',
    time: '3:00 PM-5:00 PM',
    location: 'Downtown Waxhaw',
    category: 'Family',
    description: 'A community holiday parade hosted by the Town of Waxhaw.',
    sourceUrl: 'https://www.waxhaw.com/our-town/events/volunteering-at-events',
    address: 'Downtown Waxhaw, NC 28173',
    accessibility: 'Check the official event page for route and access updates.',
  },
]

export const urgentLinks = [
  { label: 'Immediate danger', detail: 'Call 911', phone: '911' },
  { label: 'Mental health crisis', detail: 'Call or text 988', phone: '988' },
  { label: 'Domestic violence', detail: 'Turning Point: 704-283-7233', phone: '7042837233' },
  { label: 'Sexual assault', detail: 'Turning Point: 704-283-7770', phone: '7042837770' },
  { label: 'Poison Control', detail: '1-800-222-1222', phone: '18002221222' },
]

export const sourceNotes = [
  { name: 'Town of Waxhaw', url: 'https://www.waxhaw.com/', role: 'Town services, parks, programs and events' },
  { name: 'Union County Government', url: 'https://www.unioncountync.gov/', role: 'Health, social services, transportation, libraries and senior support' },
  { name: 'NC 211', url: 'https://nc211.org/', role: 'Statewide verified referral information' },
  { name: 'Union County Public Schools', url: 'https://www.ucps.k12.nc.us/', role: 'Student and family support information' },
  { name: 'Turning Point', url: 'https://turningpointnc.org/', role: 'Union County crisis services for survivors' },
  { name: 'Common Heart', url: 'https://commonheart.org/', role: 'Food pantry and economic empowerment programs' },
  { name: 'U.S. Census Bureau Geocoder', url: 'https://geocoding.geo.census.gov/geocoder/', role: 'Map coordinates for listed street addresses (public domain)' },
  { name: 'GeoNames', url: 'https://www.geonames.org/', role: 'Approximate ZIP code center points for distances (CC BY 4.0)' },
  { name: "Waxhaw's Ray of Hope", url: 'https://waxhawsrayofhope.wixsite.com/waxhaws-ray-of-hope', role: 'Local food pantry information' },
]
