export const categories = [
  { id: 'basic-needs', label: 'Basic needs', labelEs: 'Necesidades básicas', blurb: 'Food, bills and essentials', blurbEs: 'Comida, facturas y necesidades básicas' },
  { id: 'children', label: 'Children & youth', labelEs: 'Niños y jóvenes', blurb: 'Learning, care and activities', blurbEs: 'Aprendizaje, cuidado y actividades' },
  { id: 'families', label: 'Families', labelEs: 'Familias', blurb: 'Parenting and child care', blurbEs: 'Crianza y cuidado infantil' },
  { id: 'health', label: 'Health & wellness', labelEs: 'Salud y bienestar', blurb: 'Medical and mental health', blurbEs: 'Salud médica y mental' },
  { id: 'older-adults', label: 'Older adults', labelEs: 'Adultos mayores', blurb: 'Aging with support', blurbEs: 'Envejecer con apoyo' },
  { id: 'jobs', label: 'Jobs & money', labelEs: 'Empleo y finanzas', blurb: 'Training and financial stability', blurbEs: 'Capacitación y estabilidad económica' },
  { id: 'housing', label: 'Housing', labelEs: 'Vivienda', blurb: 'Rent, utilities and shelter', blurbEs: 'Renta, servicios y vivienda' },
  { id: 'transportation', label: 'Transportation', labelEs: 'Transporte', blurb: 'Rides and mobility', blurbEs: 'Transporte y movilidad' },
  { id: 'community', label: 'Community life', labelEs: 'Vida comunitaria', blurb: 'Parks, programs and connection', blurbEs: 'Parques, programas y comunidad' },
  { id: 'education', label: 'Education', labelEs: 'Educación', blurb: 'Schools and lifelong learning', blurbEs: 'Escuelas y aprendizaje continuo' },
]

export const resources = [
  {
    id: 'nc-211',
    name: 'NC 211',
    category: 'basic-needs',
    audiences: ['All ages', 'All residents'],
    description: 'Free, confidential help finding verified food, housing, health care, transportation and other services across North Carolina.',
    descriptionEs: 'Ayuda gratuita y confidencial para encontrar alimentos, vivienda, atención médica, transporte y otros servicios verificados.',
    details: 'Call 2-1-1 to speak with a Community Resource Specialist or search online. Support is available 24 hours a day, every day, in most languages.',
    phone: '211',
    alternatePhone: '888-892-1162',
    hours: 'Open 24 hours',
    cost: 'Free',
    languages: ['English', 'Spanish', 'Language support'],
    accessibility: ['Phone support', 'Online search'],
    location: 'Statewide, including Waxhaw',
    source: 'NC 211',
    sourceUrl: 'https://nc211.org/about/',
    verified: 'September 11, 2026',
    featured: true,
    alwaysOpen: true,
    keywords: ['rent', 'utility', 'food', 'shelter', 'crisis', 'benefits', 'help', 'referral'],
  },
  {
    id: 'union-economic-services',
    name: 'Union County Economic Services',
    category: 'basic-needs',
    audiences: ['Adults', 'Families', 'Older adults'],
    description: 'Apply for Food and Nutrition Services, Medicaid, child care assistance, emergency energy help and other financial-stability programs.',
    descriptionEs: 'Solicite asistencia alimentaria, Medicaid, ayuda para cuidado infantil, energía de emergencia y otros programas financieros.',
    details: 'Union County Social Services accepts applications for benefit programs and helps residents report changes to existing cases. Eligibility varies by program.',
    phone: '704-296-4300',
    hours: 'Monday-Friday, 8:00 AM-5:00 PM',
    schedule: { days: [1, 2, 3, 4, 5], start: 8, end: 17 },
    cost: 'Free to apply',
    languages: ['English', 'Spanish forms'],
    accessibility: ['Accessible office', 'Online application'],
    location: '2330 Concord Avenue, Monroe, NC 28110',
    source: 'Union County Social Services',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-r-z/social-services/economic-services',
    verified: 'September 11, 2026',
    featured: true,
    keywords: ['snap', 'ebt', 'food stamps', 'medicaid', 'childcare', 'utilities', 'lieap', 'bills', 'benefits'],
  },
  {
    id: 'union-public-health',
    name: 'Union County Public Health Clinical Services',
    category: 'health',
    audiences: ['Children', 'Adults', 'Families', 'All residents'],
    description: 'Community clinics for immunizations, dental care, family planning, maternal health, sexual health, tuberculosis treatment and more.',
    descriptionEs: 'Clínicas comunitarias de vacunas, odontología, planificación familiar, salud materna, salud sexual y tratamiento de tuberculosis.',
    details: 'Several services welcome uninsured residents. Eligibility and fees vary, so call the clinic before visiting.',
    phone: '704-296-4800',
    hours: 'Call for clinic hours',
    cost: 'Varies by service',
    languages: ['English', 'Language assistance'],
    accessibility: ['Accessible office', 'Confidential services'],
    location: '2330 Concord Avenue, Monroe, NC 28110',
    source: 'Union County Public Health',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-f-p/public-health/clinical-services',
    verified: 'September 11, 2026',
    featured: true,
    keywords: ['doctor', 'clinic', 'vaccine', 'dental', 'pregnancy', 'wic', 'uninsured', 'testing'],
  },
  {
    id: 'union-wic',
    name: 'Union County WIC',
    category: 'families',
    audiences: ['Pregnant people', 'Parents', 'Children under 5'],
    description: 'Nutrition, healthy-food and breastfeeding support for eligible pregnant people, new parents, infants and young children.',
    descriptionEs: 'Apoyo de nutrición, alimentos saludables y lactancia para personas embarazadas, padres, bebés y niños pequeños elegibles.',
    details: 'WIC services are free. Contact Union County Public Health to ask about eligibility and appointments.',
    phone: '704-296-4800',
    hours: 'Call for appointments',
    cost: 'Free for eligible families',
    languages: ['English', 'Spanish', 'Language assistance'],
    accessibility: ['Accessible office'],
    location: '2330 Concord Avenue, Monroe, NC 28110',
    source: 'Union County Public Health',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-f-p/public-health/clinical-services',
    verified: 'September 11, 2026',
    keywords: ['baby', 'infant', 'pregnant', 'nutrition', 'breastfeeding', 'food'],
  },
  {
    id: 'union-transportation',
    name: 'Union County Transportation',
    category: 'transportation',
    audiences: ['Age 16+', 'Medicaid members', 'Veterans', 'Older adults'],
    description: 'Demand-response transportation for eligible trips including medical appointments, work, errands and community activities.',
    descriptionEs: 'Transporte bajo demanda para viajes elegibles, incluidas citas médicas, trabajo, mandados y actividades comunitarias.',
    details: 'Programs have different eligibility and scheduling rules. Medicaid transportation can serve eligible residents of any age.',
    phone: '704-292-2511',
    hours: 'Call ahead to schedule',
    cost: 'Varies by program',
    languages: ['English'],
    accessibility: ['Mobility assistance', 'Advance scheduling'],
    location: 'Serves Union County',
    source: 'Union County Transportation',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-r-z/transportation/rider-s-guide',
    verified: 'September 11, 2026',
    keywords: ['ride', 'bus', 'medical transport', 'doctor', 'mobility', 'veteran', 'medicaid'],
  },
  {
    id: 'senior-nutrition',
    name: 'Union County Senior Nutrition Program',
    category: 'older-adults',
    audiences: ['Age 60+', 'Caregivers'],
    description: 'Nutritious meals through community dining sites and home delivery for eligible Union County residents age 60 and older.',
    descriptionEs: 'Comidas nutritivas en sitios comunitarios y entrega a domicilio para residentes elegibles de 60 años o más.',
    details: 'Home-delivery clients may be placed on a waiting list. Referrals and wellness checks help connect older residents with support.',
    phone: '704-283-3500',
    hours: 'Monday-Friday',
    cost: 'Call for eligibility',
    languages: ['English'],
    accessibility: ['Home delivery', 'Caregiver referrals'],
    location: 'Serves Union County',
    source: 'Union County Community Support & Outreach',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-a-e/community-support-outreach/senior-residents',
    verified: 'September 11, 2026',
    keywords: ['meals on wheels', 'senior food', 'aging', 'homebound', 'lunch'],
  },
  {
    id: 'southwest-library',
    name: 'Southwest Regional Library',
    category: 'education',
    audiences: ['Children', 'Teens', 'Adults', 'Older adults'],
    description: 'A Waxhaw library with expanded collections, children’s spaces, a STEAM lab, study rooms, technology and community programs.',
    descriptionEs: 'Biblioteca de Waxhaw con colecciones, espacios infantiles, laboratorio STEAM, salas de estudio, tecnología y programas comunitarios.',
    details: 'The approximately 19,000-square-foot branch offers space to learn, work, gather and access technology.',
    phone: '704-283-8184',
    hours: 'See library schedule',
    cost: 'Free',
    languages: ['English', 'Multilingual materials'],
    accessibility: ['Accessible building', 'Technology access', 'Study rooms'],
    location: '1515 Cuthbertson Road, Waxhaw, NC 28173',
    source: 'Union County Government',
    sourceUrl: 'https://www.unioncountync.gov/Home/Components/News/News/1433/339',
    verified: 'September 11, 2026',
    featured: true,
    keywords: ['books', 'computer', 'wifi', 'homework', 'study', 'storytime', 'steam'],
  },
  {
    id: 'waxhaw-parks',
    name: 'Waxhaw Parks & Recreation',
    category: 'community',
    audiences: ['All ages', 'All abilities'],
    description: 'Recreational, educational and cultural programs, public parks and community events designed for residents of all ages and abilities.',
    descriptionEs: 'Programas recreativos, educativos y culturales, parques públicos y eventos para residentes de todas las edades y capacidades.',
    details: 'The department manages parks, programs and town events and partners with local and regional organizations.',
    phone: '704-843-2195',
    hours: 'Monday-Friday, 8:00 AM-5:00 PM',
    schedule: { days: [1, 2, 3, 4, 5], start: 8, end: 17 },
    cost: 'Many free options',
    languages: ['English'],
    accessibility: ['Inclusive programs', 'Accessible amenities vary'],
    location: '8607 Kensington Drive, Waxhaw, NC 28173',
    source: 'Town of Waxhaw',
    sourceUrl: 'https://www.waxhaw.com/government/departments/parks-and-recreation',
    verified: 'September 11, 2026',
    keywords: ['park', 'playground', 'sports', 'recreation', 'art', 'festival', 'programs'],
  },
  {
    id: 'waxhaw-public-services',
    name: 'Waxhaw Public Services',
    category: 'housing',
    audiences: ['Residents', 'Property owners'],
    description: 'Information and assistance for trash, recycling, yard debris, seasonal leaf collection, trees, streets and sidewalks.',
    descriptionEs: 'Información y ayuda sobre basura, reciclaje, residuos de jardín, recolección de hojas, árboles, calles y aceras.',
    details: 'The Town coordinates weekly trash and biweekly recycling and maintains public streets, sidewalks and downtown grounds.',
    phone: '704-843-7439',
    hours: 'Monday-Friday, 7:00 AM-4:00 PM',
    schedule: { days: [1, 2, 3, 4, 5], start: 7, end: 16 },
    cost: 'Resident service',
    languages: ['English'],
    accessibility: ['Phone assistance', 'Online forms'],
    location: '8607 Kensington Drive, Waxhaw, NC 28173',
    source: 'Town of Waxhaw',
    sourceUrl: 'https://www.waxhaw.com/government/departments/public-services',
    verified: 'September 11, 2026',
    keywords: ['trash', 'garbage', 'recycling', 'leaves', 'streetlight', 'sidewalk'],
  },
  {
    id: 'common-heart',
    name: 'Common Heart Food Pantries',
    category: 'basic-needs',
    audiences: ['Individuals', 'Families', 'Older adults'],
    description: 'Weekly food pantries for qualifying Union County residents, including a Wednesday location in Waxhaw and delivery for residents facing transportation barriers.',
    descriptionEs: 'Despensas semanales para residentes elegibles, incluida una ubicación los miércoles en Waxhaw y entrega para quienes tienen barreras de transporte.',
    details: 'Traditional pantries provide food through TEFAP. The Common Cupboard delivery program serves qualifying Union County residents who cannot attend evening pantries.',
    phone: '980-443-3841',
    hours: 'Schedules vary by pantry',
    cost: 'Free for eligible residents',
    languages: ['English'],
    accessibility: ['Delivery for eligible residents', 'Multiple locations'],
    location: 'Waxhaw and Union County locations',
    source: 'Common Heart',
    sourceUrl: 'https://commonheart.org/programs/',
    verified: 'September 11, 2026',
    featured: true,
    keywords: ['food pantry', 'groceries', 'delivery', 'tefap', 'hunger', 'volunteer'],
  },
  {
    id: 'ray-of-hope',
    name: "Waxhaw's Ray of Hope Food Pantry",
    category: 'basic-needs',
    audiences: ['Individuals', 'Families'],
    description: 'A local food pantry serving eligible individuals and families and coordinating community food drives.',
    descriptionEs: 'Despensa local que sirve a personas y familias elegibles y coordina colectas comunitarias de alimentos.',
    details: 'The pantry states that it serves eligible people regardless of race, color, religion, national origin, age, sex or disability. Call before visiting to confirm current arrangements.',
    phone: '704-248-1017',
    hours: 'Monday-Friday, 11:00 AM-6:00 PM',
    schedule: { days: [1, 2, 3, 4, 5], start: 11, end: 18 },
    cost: 'Free for eligible residents',
    languages: ['English'],
    accessibility: ['Call for accommodations'],
    location: 'Waxhaw, NC',
    source: "Waxhaw's Ray of Hope",
    sourceUrl: 'https://waxhawsrayofhope.wixsite.com/waxhaws-ray-of-hope/food-pantry',
    verified: 'September 11, 2026',
    keywords: ['food pantry', 'groceries', 'hunger', 'food drive'],
  },
  {
    id: 'turning-point',
    name: 'Turning Point',
    category: 'housing',
    audiences: ['Survivors', 'Adults', 'Children', 'Families'],
    description: 'Free emergency shelter, crisis response and advocacy for survivors of domestic violence, sexual assault and child abuse in Union County.',
    descriptionEs: 'Refugio de emergencia, respuesta a crisis y defensa gratuitas para sobrevivientes de violencia doméstica, agresión sexual y abuso infantil.',
    details: 'The shelter location is confidential for safety. Turning Point provides crisis intervention, safety planning, counseling, court advocacy and children’s services.',
    phone: '704-283-7233',
    alternatePhone: '704-283-7770',
    hours: 'Crisis lines open 24 hours',
    cost: 'Free',
    languages: ['English', 'Call for language support'],
    accessibility: ['Confidential shelter', 'Crisis advocacy'],
    location: 'Confidential location, Union County',
    confidentialLocation: true,
    source: 'Turning Point',
    sourceUrl: 'https://turningpointnc.org/',
    verified: 'September 11, 2026',
    alwaysOpen: true,
    urgent: true,
    keywords: ['domestic violence', 'sexual assault', 'abuse', 'safe shelter', 'crisis', 'escape'],
  },
  {
    id: 'work-first',
    name: 'Union County Work First',
    category: 'jobs',
    audiences: ['Families', 'Parents', 'Job seekers'],
    description: 'Temporary financial support and employment services that help families work toward stability and self-sufficiency.',
    descriptionEs: 'Apoyo financiero temporal y servicios de empleo para ayudar a las familias a lograr estabilidad y autosuficiencia.',
    details: 'The program focuses on job readiness, employment, child well-being and family health. Applications can be submitted online or by email.',
    phone: '704-296-4300',
    hours: 'Monday-Friday, 8:00 AM-5:00 PM',
    schedule: { days: [1, 2, 3, 4, 5], start: 8, end: 17 },
    cost: 'Free to apply',
    languages: ['English', 'Spanish forms'],
    accessibility: ['Online application', 'Accessible office'],
    location: 'Serves Union County',
    source: 'Union County Community Support & Outreach',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-a-e/community-support-outreach/work-first',
    verified: 'September 11, 2026',
    keywords: ['job', 'cash assistance', 'employment', 'training', 'parents', 'benefits'],
  },
  {
    id: 'child-care-subsidy',
    name: 'Union County Child Care Subsidy',
    category: 'families',
    audiences: ['Parents', 'Caregivers', 'Children'],
    description: 'Income-based assistance with child care costs for eligible families who have a qualifying child care need.',
    descriptionEs: 'Ayuda basada en ingresos para cubrir el cuidado infantil de familias elegibles con una necesidad calificada.',
    details: 'The program also helps parents understand how to select safe, quality child care. Contact the county’s vendor to ask about current eligibility.',
    phone: '704-706-9494',
    hours: 'Call for assistance',
    cost: 'Income-based assistance',
    languages: ['English'],
    accessibility: ['Phone assistance'],
    location: 'Serves Union County',
    source: 'Union County Social Services',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-r-z/social-services/economic-services',
    verified: 'September 11, 2026',
    keywords: ['daycare', 'childcare', 'preschool', 'babysitting', 'working parent'],
  },
  {
    id: 'ucps-family-resources',
    name: 'UCPS Community & Mental Health Resources',
    category: 'children',
    audiences: ['Students', 'Parents', 'Caregivers'],
    description: 'A school-system resource collection connecting students and families with community and behavioral-health support.',
    descriptionEs: 'Colección del sistema escolar que conecta a estudiantes y familias con apoyo comunitario y de salud mental.',
    details: 'The guide includes local social services, child and family supports, behavioral-health providers and crisis resources.',
    phone: '704-296-9898',
    hours: 'See school-system information',
    cost: 'Information is free',
    languages: ['English'],
    accessibility: ['Online directory', 'School support'],
    location: 'Serves Union County Public Schools families',
    source: 'Union County Public Schools',
    sourceUrl: 'https://fhhs.ucpsnc.org/students-families/parent-resources/community-mental-health-resources',
    verified: 'September 11, 2026',
    keywords: ['school', 'student', 'counseling', 'mental health', 'parent', 'teen'],
  },
  {
    id: 'veterans-services',
    name: 'Union County Veterans Services',
    category: 'older-adults',
    audiences: ['Veterans', 'Service members', 'Families'],
    description: 'County assistance connecting veterans and their families with benefits, services and eligible transportation.',
    descriptionEs: 'Ayuda del condado para conectar a veteranos y sus familias con beneficios, servicios y transporte elegible.',
    details: 'Contact the office to ask about benefits counseling and documentation needed for an appointment.',
    phone: '704-283-3807',
    hours: 'Call for an appointment',
    cost: 'Free assistance',
    languages: ['English'],
    accessibility: ['Office assistance', 'Transportation referrals'],
    location: '407 North Main Street, Monroe, NC 28112',
    source: 'Union County Government',
    sourceUrl: 'https://www.unioncountync.gov/government/departments-f-p/public-communications/union-county-office-addresses-and-phone-numbers',
    verified: 'September 11, 2026',
    keywords: ['veteran', 'military', 'benefits', 'va', 'service member'],
  },
  {
    id: 'atrium-waxhaw',
    name: 'Atrium Health Waxhaw Emergency Department',
    category: 'health',
    audiences: ['All ages', 'All residents'],
    description: 'A freestanding emergency department in Waxhaw with emergency physicians and advanced diagnostic services.',
    descriptionEs: 'Departamento de emergencias independiente en Waxhaw con médicos de emergencia y servicios de diagnóstico avanzados.',
    details: 'For life-threatening emergencies, call 911. This listing is for emergency medical care, not routine primary care.',
    phone: '911',
    hours: 'Emergency care open 24 hours',
    cost: 'Insurance and fees vary',
    languages: ['English', 'Language assistance'],
    accessibility: ['Accessible facility', 'Emergency care'],
    location: '2700 Providence Road South, Waxhaw, NC 28173',
    source: 'Union County Health and Wellness Resource Guide',
    sourceUrl: 'https://www.unioncountync.gov/home/showpublisheddocument/1178/639148218369100000',
    verified: 'September 11, 2026',
    alwaysOpen: true,
    urgent: true,
    keywords: ['hospital', 'emergency room', 'er', 'urgent medical', 'injury'],
  },
]

export const events = [
  {
    id: 'jammin-tracks-sept',
    title: "Jammin' By The Tracks",
    date: '2026-09-18',
    time: '7:00 PM-9:00 PM',
    location: 'Community Corner, 115 McDonald Street',
    category: 'Music',
    description: 'A free outdoor concert under the Water Tank featuring Darren Deese.',
    descriptionEs: 'Un concierto gratuito al aire libre bajo el tanque de agua con Darren Deese.',
    sourceUrl: 'https://www.waxhaw.com/our-town/events/jammin-by-the-tracks',
    address: '115 McDonald Street, Waxhaw, NC 28173',
    accessibility: 'Outdoor venue; contact organizers for accommodations.',
    accessibilityEs: 'Lugar al aire libre; comuníquese con los organizadores para solicitar adaptaciones.',
  },
  {
    id: 'library-board-sept',
    title: 'Union County Library Board Meeting',
    date: '2026-09-15',
    time: '5:30 PM',
    location: 'Southwest Regional Library, Waxhaw',
    category: 'Civic',
    description: 'A scheduled public meeting of the Union County Library Board of Trustees.',
    descriptionEs: 'Una reunión pública programada de la Junta Directiva de la Biblioteca de Union County.',
    sourceUrl: 'https://www.unioncountync.gov/government/boards-committees/board-of-county-commissioners/commissioner-appointments-to-boards-committees',
    address: '1515 Cuthbertson Road, Waxhaw, NC 28173',
    accessibility: 'Accessible public building.',
    accessibilityEs: 'Edificio público accesible.',
  },
  {
    id: 'autumn-treasures',
    title: 'Autumn Treasures',
    date: '2026-10-10',
    time: '10:00 AM-6:00 PM',
    location: 'Downtown Waxhaw',
    category: 'Festival',
    description: 'Waxhaw’s annual festival with local makers, music, food and a family area. Admission is free.',
    descriptionEs: 'El festival anual de Waxhaw con creadores locales, música, comida y un área familiar. La entrada es gratuita.',
    sourceUrl: 'https://www.waxhaw.com/our-town/events/autumn-treasures',
    address: 'Downtown Waxhaw, NC 28173',
    accessibility: 'ADA parking is listed by the Town of Waxhaw.',
    accessibilityEs: 'Town of Waxhaw publica información sobre estacionamiento accesible según la ADA.',
  },
  {
    id: 'christmas-parade',
    title: 'Waxhaw Christmas Parade',
    date: '2026-12-13',
    time: '3:00 PM-5:00 PM',
    location: 'Downtown Waxhaw',
    category: 'Family',
    description: 'A community holiday parade hosted by the Town of Waxhaw.',
    descriptionEs: 'Un desfile comunitario de temporada organizado por Town of Waxhaw.',
    sourceUrl: 'https://www.waxhaw.com/our-town/events/volunteering-at-events',
    address: 'Downtown Waxhaw, NC 28173',
    accessibility: 'Check the official event page for route and access updates.',
    accessibilityEs: 'Consulte la página oficial del evento para ver actualizaciones sobre la ruta y el acceso.',
  },
  {
    id: 'movie-in-the-park-sept',
    title: 'Movie In The Park',
    date: '2026-09-26',
    time: '6:00 PM-9:00 PM',
    location: 'Waxhaw Downtown Park, 301 Givens Street',
    address: '301 Givens Street, Waxhaw, NC 28173',
    category: 'Family',
    description: 'A free outdoor family movie night hosted by the town, with activities before the film starts. Bring a blanket or lawn chairs.',
    descriptionEs: 'Una noche de cine familiar gratuita al aire libre organizada por el pueblo, con actividades antes de la película. Lleve una manta o sillas de jardín.',
    sourceUrl: 'https://www.waxhaw.com/our-town/town-calendar',
    accessibility: 'Outdoor park; seating is on the grass, so bring your own chairs.',
    accessibilityEs: 'Parque al aire libre; se sienta en el césped, así que lleve sus propias sillas.',
  },
  {
    id: 'monroe-denim-dolly',
    title: 'Meet Me on Main: Denim & Dolly',
    date: '2026-09-25',
    time: '6:00 PM-9:00 PM',
    location: 'Morgan-Windsor Alley and Main Street, Downtown Monroe',
    address: 'Main Street, Monroe, NC 28112',
    category: 'Arts & Culture',
    description: 'A free downtown gathering centered on ages 16 to 24, with a silent disco, pumpkin painting, games, local business specials and easy access to Music on Main.',
    descriptionEs: 'Una reunión gratuita en el centro, pensada especialmente para personas de 16 a 24 años, con discoteca silenciosa, pintura de calabazas, juegos y ofertas de negocios locales.',
    sourceUrl: 'https://www.monroenc.org/731/Meet-Me-on-Main-Student-Events',
    accessibility: 'Free to attend. Activities are spread across downtown alleys and Main Street; contact the City of Monroe for access details.',
    accessibilityEs: 'La entrada es gratuita. Las actividades se distribuyen entre los callejones del centro y Main Street; comuníquese con City of Monroe para conocer los detalles de acceso.',
  },
  {
    id: 'indian-trail-senior-fest',
    title: 'Senior Fest',
    date: '2026-09-30',
    time: '9:00 AM-1:00 PM',
    location: 'Indian Trail Town Hall',
    address: '315 Matthews-Indian Trail Road, Indian Trail, NC 28079',
    category: 'Wellness',
    description: 'A community day for adults 55 and older with a cookout, games and activities designed to help local seniors connect.',
    descriptionEs: 'Un día comunitario para adultos de 55 años o más con comida al aire libre, juegos y actividades para conectar a las personas mayores de la zona.',
    sourceUrl: 'https://www.indiantrail.org/Calendar.aspx',
    accessibility: 'Held at Indian Trail Town Hall. Contact Parks and Recreation for accommodation or registration details.',
    accessibilityEs: 'Se realiza en Indian Trail Town Hall. Comuníquese con Parks and Recreation para solicitar adaptaciones o información de inscripción.',
  },
  {
    id: 'monroe-sound-of-julie',
    title: 'The Sound of Julie',
    date: '2026-10-02',
    time: '7:30 PM',
    location: 'Dowd Center Theatre, Monroe',
    address: '120 South Main Street, Monroe, NC 28112',
    category: 'Music',
    description: 'A family-friendly live concert celebrating the music of Julie Andrews, performed by British vocalist Hayley Renee at the Dowd Center Theatre.',
    descriptionEs: 'Un concierto familiar en vivo que celebra la música de Julie Andrews, interpretado por la cantante británica Hayley Renee en Dowd Center Theatre.',
    sourceUrl: 'https://www.monroenc.org/710/The-Sound-of-Julie',
    accessibility: 'Doors open at 6:30 p.m. Tickets are required; contact the Dowd Center Theatre for seating and accessibility arrangements.',
    accessibilityEs: 'Las puertas abren a las 6:30 p. m. Se requieren boletos; comuníquese con Dowd Center Theatre para consultar sobre asientos y accesibilidad.',
  },
  {
    id: 'matthews-beats-bites-october',
    title: "Beats 'n Bites: Chairmen of the Board",
    date: '2026-10-02',
    time: '5:00 PM-9:00 PM',
    location: 'Stumptown Park, Matthews',
    address: '120 South Trade Street, Matthews, NC 28105',
    category: 'Music',
    description: 'An evening of live beach music, food trucks and community time in Stumptown Park. Music begins at 6 p.m.; bring chairs or a blanket.',
    descriptionEs: 'Una noche de música playera en vivo, camiones de comida y convivencia comunitaria en Stumptown Park. La música comienza a las 6 p. m.; lleve sillas o una manta.',
    sourceUrl: 'https://www.matthewsnc.gov/newsview.aspx?nid=7161',
    accessibility: 'Designated accessible parking is available along Trade Street and at the Matthews Free Medical Clinic. Service dogs are welcome.',
    accessibilityEs: 'Hay estacionamiento accesible designado en Trade Street y en Matthews Free Medical Clinic. Se permiten perros de servicio.',
  },
  {
    id: 'monroe-car-cruise-october',
    title: 'Downtown Monroe Car Cruise-In',
    date: '2026-10-09',
    time: '6:00 PM-8:00 PM',
    location: 'Main Street, Downtown Monroe',
    address: 'Main Street, Monroe, NC 28112',
    category: 'Festival',
    description: 'The final Car Cruise-In of the 2026 season brings classic cars, custom builds and conversations with vehicle owners to Main Street.',
    descriptionEs: 'El último encuentro de autos de la temporada 2026 lleva autos clásicos, vehículos personalizados y conversaciones con sus dueños a Main Street.',
    sourceUrl: 'https://www.monroenc.org/Calendar.aspx?EID=2899&calType=0&day=11&month=10&year=2026',
    accessibility: 'Free to attend on Main Street. Contact the City of Monroe for accessible parking or route details.',
    accessibilityEs: 'La entrada es gratuita en Main Street. Comuníquese con City of Monroe para consultar sobre estacionamiento accesible o detalles del recorrido.',
  },
  {
    id: 'monroe-halloween-happenings',
    title: 'Halloween Happenings',
    date: '2026-10-17',
    time: '11:00 AM-3:00 PM',
    location: 'Downtown Monroe',
    address: 'Main Street, Monroe, NC 28112',
    category: 'Family',
    description: 'The City of Monroe’s annual downtown fall festival returns to Main Street with family Halloween activities. Check the official listing as more details are released.',
    descriptionEs: 'El festival familiar de otoño de City of Monroe regresa a Main Street con actividades de Halloween. Consulte el anuncio oficial a medida que se publiquen más detalles.',
    sourceUrl: 'https://monroenc.org/m/calendar/event/detail/2920',
    accessibility: 'Outdoor downtown event. Confirm accessible parking and event details with the City before attending.',
    accessibilityEs: 'Evento al aire libre en el centro. Confirme el estacionamiento accesible y los detalles con la ciudad antes de asistir.',
  },
  {
    id: 'indian-trail-spooktacular',
    title: 'Indian Trail Spooktacular',
    date: '2026-10-23',
    time: '6:00 PM-9:00 PM',
    location: 'Chestnut Square Park, Indian Trail',
    address: '320 Chestnut Parkway, Indian Trail, NC 28079',
    category: 'Family',
    description: 'A family Halloween celebration with a large trunk-or-treat, themed craft, dance party and other seasonal activities at Chestnut Square Park.',
    descriptionEs: 'Una celebración familiar de Halloween con entrega de dulces desde autos decorados, manualidades temáticas, fiesta de baile y otras actividades en Chestnut Square Park.',
    sourceUrl: 'https://www.indiantrail.org/1770/Events',
    accessibility: 'Chestnut Square Park lists parking, benches, paved walking areas, restrooms and playground amenities.',
    accessibilityEs: 'Chestnut Square Park cuenta con estacionamiento, bancos, senderos pavimentados, baños y áreas de juego.',
  },
  {
    id: 'monroe-christmas-parade',
    title: 'Monroe Christmas Parade',
    date: '2026-11-22',
    time: '2:00 PM',
    location: 'Historic Downtown Monroe',
    address: 'Main Street, Monroe, NC 28112',
    category: 'Family',
    description: 'Monroe’s holiday parade brings more than 100 floats, marching bands, classic cars and community groups through historic downtown.',
    descriptionEs: 'El desfile navideño de Monroe reúne más de 100 carrozas, bandas de marcha, autos clásicos y grupos comunitarios en el centro histórico.',
    sourceUrl: 'https://monroenc.org/733/Monroe-Christmas-Parade',
    accessibility: 'A quieter sensory viewing area is planned near Jefferson and North Church streets. Check the official page for the final route and parking map.',
    accessibilityEs: 'Se planea una zona sensorial más tranquila cerca de Jefferson y North Church. Consulte la página oficial para ver el recorrido final y el mapa de estacionamiento.',
  },
  {
    id: 'boc-regular',
    title: 'Waxhaw Board of Commissioners Regular Meeting',
    recurrence: { week: 2, weekday: 2 },
    time: '6:30 PM',
    location: 'Waxhaw Town Hall, 4218 Waxhaw-Marvin Road',
    address: '4218 Waxhaw-Marvin Road, Waxhaw, NC 28173',
    category: 'Civic',
    description: 'The board’s monthly public meeting, held on the second Tuesday. Residents may sign up to speak during the public comment period. Confirm the agenda on the town calendar before attending.',
    descriptionEs: 'La reunión pública mensual de la junta, el segundo martes de cada mes. Los residentes pueden inscribirse para hablar durante el periodo de comentarios. Confirme la agenda en el calendario del pueblo antes de asistir.',
    sourceUrl: 'https://www.waxhaw.com/our-town/town-calendar',
    accessibility: 'Open to the public at Town Hall. Agendas are posted before each meeting, and meetings are livestreamed on the town YouTube channel.',
    accessibilityEs: 'Abierta al público en el Ayuntamiento. Las agendas se publican antes de cada reunión y las reuniones se transmiten en el canal de YouTube del pueblo.',
  },
  {
    id: 'boc-work-session',
    title: 'Waxhaw Board of Commissioners Work Session',
    recurrence: { week: 4, weekday: 2 },
    time: '6:30 PM',
    location: 'Waxhaw Town Hall, 4218 Waxhaw-Marvin Road',
    address: '4218 Waxhaw-Marvin Road, Waxhaw, NC 28173',
    category: 'Civic',
    description: 'A working meeting on the fourth Tuesday where commissioners discuss upcoming items in more detail. Open to the public. Confirm the agenda on the town calendar before attending.',
    descriptionEs: 'Una reunión de trabajo el cuarto martes, donde los comisionados analizan con más detalle los temas próximos. Abierta al público. Confirme la agenda en el calendario del pueblo antes de asistir.',
    sourceUrl: 'https://www.waxhaw.com/our-town/town-calendar',
    accessibility: 'Open to the public at Town Hall. Agendas are posted before each meeting, and meetings are livestreamed on the town YouTube channel.',
    accessibilityEs: 'Abierta al público en el Ayuntamiento. Las agendas se publican antes de cada reunión y las reuniones se transmiten en el canal de YouTube del pueblo.',
  },
  {
    id: 'planning-board',
    title: 'Waxhaw Planning Board Regular Meeting',
    recurrence: { week: 3, weekday: 2 },
    time: '6:30 PM',
    location: 'Waxhaw Town Hall, 4218 Waxhaw-Marvin Road',
    address: '4218 Waxhaw-Marvin Road, Waxhaw, NC 28173',
    category: 'Civic',
    description: 'The board that reviews rezonings and development proposals meets on the third Tuesday. This is where neighbors can hear about projects near them. Confirm the agenda on the town calendar before attending.',
    descriptionEs: 'La junta que revisa las rezonificaciones y las propuestas de desarrollo se reúne el tercer martes. Aquí los vecinos pueden enterarse de los proyectos cerca de ellos. Confirme la agenda en el calendario del pueblo antes de asistir.',
    sourceUrl: 'https://www.waxhaw.com/our-town/town-calendar',
    accessibility: 'Open to the public at Town Hall. Agendas are posted before each meeting, and meetings are livestreamed on the town YouTube channel.',
    accessibilityEs: 'Abierta al público en el Ayuntamiento. Las agendas se publican antes de cada reunión y las reuniones se transmiten en el canal de YouTube del pueblo.',
  },
  {
    id: 'parks-recreation-board',
    title: 'Waxhaw Parks, Cultural and Recreation Board',
    recurrence: { week: 3, weekday: 3 },
    time: '6:30 PM',
    location: 'Waxhaw Town Hall, 4218 Waxhaw-Marvin Road',
    address: '4218 Waxhaw-Marvin Road, Waxhaw, NC 28173',
    category: 'Civic',
    description: 'The advisory board for parks, greenways and town programs meets on the third Wednesday. Confirm the agenda on the town calendar before attending.',
    descriptionEs: 'La junta asesora de parques, senderos y programas del pueblo se reúne el tercer miércoles. Confirme la agenda en el calendario del pueblo antes de asistir.',
    sourceUrl: 'https://www.waxhaw.com/our-town/town-calendar',
    accessibility: 'Open to the public at Town Hall. Agendas are posted before each meeting, and meetings are livestreamed on the town YouTube channel.',
    accessibilityEs: 'Abierta al público en el Ayuntamiento. Las agendas se publican antes de cada reunión y las reuniones se transmiten en el canal de YouTube del pueblo.',
  },
  {
    id: 'historic-preservation',
    title: 'Waxhaw Historic Preservation Commission',
    recurrence: { week: 2, weekday: 4 },
    time: '6:30 PM',
    location: 'Waxhaw Town Hall, 4218 Waxhaw-Marvin Road',
    address: '4218 Waxhaw-Marvin Road, Waxhaw, NC 28173',
    category: 'Civic',
    description: 'The commission that reviews changes to historic downtown properties meets on the second Thursday. Confirm the agenda on the town calendar before attending.',
    descriptionEs: 'La comisión que revisa los cambios en las propiedades históricas del centro se reúne el segundo jueves. Confirme la agenda en el calendario del pueblo antes de asistir.',
    sourceUrl: 'https://www.waxhaw.com/our-town/town-calendar',
    accessibility: 'Open to the public at Town Hall. Agendas are posted before each meeting, and meetings are livestreamed on the town YouTube channel.',
    accessibilityEs: 'Abierta al público en el Ayuntamiento. Las agendas se publican antes de cada reunión y las reuniones se transmiten en el canal de YouTube del pueblo.',
  },
]

export const urgentLinks = [
  { label: 'Immediate danger', labelEs: 'Peligro inmediato', detail: 'Call 911', detailEs: 'Llame al 911', phone: '911' },
  { label: 'Mental health crisis', labelEs: 'Crisis de salud mental', detail: 'Call or text 988', detailEs: 'Llame o mande un texto al 988', phone: '988' },
  { label: 'Domestic violence', labelEs: 'Violencia doméstica', detail: 'Turning Point: 704-283-7233', detailEs: 'Turning Point: 704-283-7233', phone: '7042837233' },
  { label: 'Sexual assault', labelEs: 'Agresión sexual', detail: 'Turning Point: 704-283-7770', detailEs: 'Turning Point: 704-283-7770', phone: '7042837770' },
  { label: 'Poison Control', labelEs: 'Centro de Envenenamiento', detail: '1-800-222-1222', detailEs: '1-800-222-1222', phone: '18002221222' },
]

export const sourceNotes = [
  { name: 'Town of Waxhaw', url: 'https://www.waxhaw.com/', role: 'Town services, parks, programs and events' },
  { name: 'City of Monroe', url: 'https://www.monroenc.org/', role: 'Official Monroe community events and public programs' },
  { name: 'Town of Indian Trail', url: 'https://www.indiantrail.org/', role: 'Official Indian Trail events, parks and recreation programs' },
  { name: 'Town of Matthews', url: 'https://www.matthewsnc.gov/', role: 'Official Matthews events, parks and public programs' },
  { name: 'Union County Government', url: 'https://www.unioncountync.gov/', role: 'Health, social services, transportation, libraries and senior support' },
  { name: 'NC 211', url: 'https://nc211.org/', role: 'Statewide verified referral information' },
  { name: 'Union County Public Schools', url: 'https://www.ucps.k12.nc.us/', role: 'Student and family support information' },
  { name: 'Turning Point', url: 'https://turningpointnc.org/', role: 'Union County crisis services for survivors' },
  { name: 'Common Heart', url: 'https://commonheart.org/', role: 'Food pantry and economic empowerment programs' },
  { name: 'U.S. Census Bureau Geocoder', url: 'https://geocoding.geo.census.gov/geocoder/', role: 'Map coordinates for listed street addresses (public domain)' },
  { name: 'GeoNames', url: 'https://www.geonames.org/', role: 'Approximate ZIP code center points for distances (CC BY 4.0)' },
  { name: "Waxhaw's Ray of Hope", url: 'https://waxhawsrayofhope.wixsite.com/waxhaws-ray-of-hope', role: 'Local food pantry information' },
]
