/**
 * Generated by `npm run geocode` from the U.S. Census Bureau Geocoder
 * (public domain). Do not edit by hand; change the address in data.js and
 * rerun the script. Addresses missing here fall back to ZIP-based distances.
 */
export const GEOCODED = {
  "115 McDonald Street, Waxhaw, NC 28173": {
    "lat": 34.92578,
    "lng": -80.743978,
    "matched": "115 MCDONALD ST, WAXHAW, NC, 28173"
  },
  "1515 Cuthbertson Road, Waxhaw, NC 28173": {
    "lat": 34.972472,
    "lng": -80.738979,
    "matched": "1515 CUTHBERTSON RD, WAXHAW, NC, 28173"
  },
  "2330 Concord Avenue, Monroe, NC 28110": {
    "lat": 35.012249,
    "lng": -80.544938,
    "matched": "2330 CONCORD AVE, MONROE, NC, 28110"
  },
  "2700 Providence Road South, Waxhaw, NC 28173": {
    "lat": 34.964808,
    "lng": -80.763671,
    "matched": "2700 PROVIDENCE RD S, WAXHAW, NC, 28173"
  },
  "407 North Main Street, Monroe, NC 28112": {
    "lat": 34.983378,
    "lng": -80.550457,
    "matched": "407 N MAIN ST, MONROE, NC, 28112"
  },
  "4218 Waxhaw-Marvin Road, Waxhaw, NC 28173": {
    "lat": 34.946431,
    "lng": -80.773429,
    "matched": "4218 WAXHAW-MARVIN RD, WAXHAW, NC, 28173"
  },
  "8607 Kensington Drive, Waxhaw, NC 28173": {
    "lat": 34.946798,
    "lng": -80.773555,
    "matched": "8607 KENSINGTON DR, WAXHAW, NC, 28173"
  }
}
